Avoid circular elaboration in SK.CPU_Info
The binder issues the following error:

 error: Elaboration circularity detected
 info:
 info:    Reason:
 info:
 info:      unit "sk.cpu_info (spec)" depends on its own elaboration
 info:
 info:    Circularity:
 info:
 info:      unit "sk.cpu_info (spec)" has with clause and pragma Elaborate_All for unit "sk.apic (spec)"
 info:      unit "sk.apic (body)" is in the closure of pragma Elaborate_All
 info:      unit "sk.apic (body)" has with clause for unit "sk.delays (spec)"
 info:      unit "sk.delays (body)" is in the closure of pragma Elaborate_All
 info:      unit "sk.delays (body)" has with clause for unit "sk.arch (spec)"
 info:      unit "sk.arch (body)" is in the closure of pragma Elaborate_All
 info:      unit "sk.arch (body)" has with clause for unit "sk.vmx (spec)"
 info:      unit "sk.vmx (spec)" has with clause for unit "sk.cpu_info (spec)"
 info:
 info:    Suggestions:
 info:
 info:      change pragma Elaborate_All for unit "sk.apic (spec)" to Elaborate in unit "sk.cpu_info (spec)"
 info:      remove pragma Elaborate_All for unit "sk.apic (spec)" in unit "sk.cpu_info (spec)"
 info:      diagnose all circularities (binder switch -d_C)
 info:

Follow the suggestion and convert the Elaborate_All (SK.APIC) to an
Elaborate.